# Generated by Django 6.1 on 2026-09-02 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito / Débito'), ('SIPAP', 'Transferencia Bancaria (SIPAP)'), ('EFECTIVO', 'Efectivo en Caja')], help_text='Tipo de método de pago nacional habilitado.', max_length=20)),
                ('nombre_titular', models.CharField(help_text='Nombre completo del titular de la cuenta o tarjeta.', max_length=150, verbose_name='Nombre del Titular')),
                ('banco_emisor', models.CharField(blank=True, help_text='Entidad bancaria o financiera emisora (ej. Itaú, Continental).', max_length=100, null=True, verbose_name='Banco Emisor')),
                ('numero_enmascarado', models.CharField(help_text='Número o identificador enmascarado. Ej: **** 4321 o Alias CBU/Cuenta.', max_length=30)),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Indica si es el medio de pago seleccionado por defecto.', verbose_name='¿Es Predeterminado?')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico).')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro en el sistema.')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario de este medio de pago.', on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'ordering': ['-es_predeterminado', '-creado_en'],
            },
        ),
    ]
