# Generated by Django 6.1 on 2026-09-29 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_usuaciocliente_usuariocliente'),
        ('mpagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente al que pertenece este medio de pago.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='clientes.cliente'),
        ),
    ]
