# Generated by Django 6.1 on 2026-08-31 02:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuacioCliente',
            new_name='UsuarioCliente',
        ),
    ]
