# Generated by Django 6.1 on 2026-10-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_usuaciocliente_usuariocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='rol_cliente',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20),
        ),
    ]
