# Generated by Django 6.1 on 2026-09-11 03:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaDeCambio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tasa_base', models.DecimalField(decimal_places=4, max_digits=12)),
                ('margen_compra', models.DecimalField(decimal_places=4, max_digits=12)),
                ('margen_venta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha_vigencia', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas', to='operaciones.moneda')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha_vigencia'],
            },
        ),
    ]
