# Generated by Django 6.1 on 2026-09-29 04:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_usuaciocliente_usuariocliente'),
        ('mpagos', '0002_mediopago_cliente'),
        ('operaciones', '0002_tasadecambio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionComision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], max_length=20, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra de divisa'), ('VENTA', 'Venta de divisa')], max_length=10)),
                ('monto_origen', models.DecimalField(decimal_places=4, max_digits=18)),
                ('monto_destino', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('categoria_cliente_aplicada', models.CharField(choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], max_length=20)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_comision', models.DecimalField(decimal_places=4, max_digits=18)),
                ('moneda_comision', models.CharField(max_length=3)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='clientes.cliente')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='mpagos.mediopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='operaciones.moneda')),
                ('tasa_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='operaciones.tasadecambio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
