# Generated by Django 6.1.1 on 2026-09-28 15:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_usuaciocliente_usuariocliente'),
        ('mpagos', '0001_initial'),
        ('operaciones', '0002_tasadecambio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_recibido', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, max_digits=12)),
                ('facturada', models.BooleanField(default=False)),
                ('dispositivo', models.CharField(choices=[('IPHONE', 'iPhone'), ('IPAD', 'iPad'), ('ANDROID', 'Android'), ('WINDOWS', 'PC (Windows)'), ('MAC', 'Mac'), ('LINUX', 'PC (Linux)'), ('OTRO', 'Otro')], default='OTRO', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_atendidas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='clientes.cliente')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='mpagos.mediopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='operaciones.moneda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['cliente', '-fecha'], name='operaciones_cliente_6f0f96_idx')],
            },
        ),
    ]
